input:
  reader: read_csv_file
  data_directory: './example/input'
  variable_map: './example_data/variable_map.dat'
  missing_values: [-999.99, -999.0]
  missing_characters: ['na']
  manipulations:
  -
    widget: 'widget_template'
    do_it: true
    inputs:
      method_arg_1: 'blue'
      method_arg_2: 'green'

output:
  data_directory: './example/output'
  writer: 'write_csv_file'
  manipulations:
  -
    widget: 'widget_template'
    do_it: true
    with_header: False
    input_columns: []
    inputs:
      method_arg_1: 'yellow'
      method_arg_2: 'white'
    output_columns: []
  -
    widget: 'add_constant'
    do_it: true
    with_header: True
    input_columns: [4]
    inputs:
      constant: 1.0
      missing_value: -999.99
    output_columns: [1]
  -
    widget: 'widget_template'
    do_it: true
    input_columns: []
    inputs:
      method_arg_1: 'elf'
      method_arg_2: 'santa'
